//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFe_Util_HM.NFeRetAutorizacao4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", ConfigurationName="NFeRetAutorizacao4.NFeRetAutorizacao4Soap12")]
    public interface NFeRetAutorizacao4Soap12 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeRetAutorizacaoLote não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4/nfeRetAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse nfeRetAutorizacaoLote(DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4/nfeRetAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse> nfeRetAutorizacaoLoteAsync(DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRetAutorizacaoLoteRequest() {
        }
        
        public nfeRetAutorizacaoLoteRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeRetAutorizacaoLoteResponse() {
        }
        
        public nfeRetAutorizacaoLoteResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeRetAutorizacao4Soap12Channel : DFe_Util_HM.NFeRetAutorizacao4.NFeRetAutorizacao4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeRetAutorizacao4Soap12Client : System.ServiceModel.ClientBase<DFe_Util_HM.NFeRetAutorizacao4.NFeRetAutorizacao4Soap12>, DFe_Util_HM.NFeRetAutorizacao4.NFeRetAutorizacao4Soap12 {
        
        public NFeRetAutorizacao4Soap12Client() {
        }
        
        public NFeRetAutorizacao4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeRetAutorizacao4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRetAutorizacao4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRetAutorizacao4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse DFe_Util_HM.NFeRetAutorizacao4.NFeRetAutorizacao4Soap12.nfeRetAutorizacaoLote(DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request) {
            return base.Channel.nfeRetAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeRetAutorizacaoLote(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest inValue = new DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse retVal = ((DFe_Util_HM.NFeRetAutorizacao4.NFeRetAutorizacao4Soap12)(this)).nfeRetAutorizacaoLote(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse> DFe_Util_HM.NFeRetAutorizacao4.NFeRetAutorizacao4Soap12.nfeRetAutorizacaoLoteAsync(DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request) {
            return base.Channel.nfeRetAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse> nfeRetAutorizacaoLoteAsync(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest inValue = new DFe_Util_HM.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((DFe_Util_HM.NFeRetAutorizacao4.NFeRetAutorizacao4Soap12)(this)).nfeRetAutorizacaoLoteAsync(inValue);
        }
    }
}
