//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFe_Util_HM.NFeAutorizacao4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", ConfigurationName="NFeAutorizacao4.NFeAutorizacao4Soap12")]
    public interface NFeAutorizacao4Soap12 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeAutorizacaoLote não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteResponse nfeAutorizacaoLote(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeAutorizacaoLoteZip não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse nfeAutorizacaoLoteZip(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeAutorizacaoLoteRequest() {
        }
        
        public nfeAutorizacaoLoteRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteResponse() {
        }
        
        public nfeAutorizacaoLoteResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public string nfeDadosMsgZip;
        
        public nfeAutorizacaoLoteZipRequest() {
        }
        
        public nfeAutorizacaoLoteZipRequest(string nfeDadosMsgZip) {
            this.nfeDadosMsgZip = nfeDadosMsgZip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteZipResponse() {
        }
        
        public nfeAutorizacaoLoteZipResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeAutorizacao4Soap12Channel : DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeAutorizacao4Soap12Client : System.ServiceModel.ClientBase<DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12>, DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12 {
        
        public NFeAutorizacao4Soap12Client() {
        }
        
        public NFeAutorizacao4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeAutorizacao4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteResponse DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12.nfeAutorizacaoLote(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLote(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest inValue = new DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteResponse retVal = ((DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLote(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteResponse> DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12.nfeAutorizacaoLoteAsync(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest inValue = new DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12.nfeAutorizacaoLoteZip(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZip(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLoteZip(string nfeDadosMsgZip) {
            DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest inValue = new DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse retVal = ((DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLoteZip(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse> DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12.nfeAutorizacaoLoteZipAsync(DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(string nfeDadosMsgZip) {
            DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest inValue = new DFe_Util_HM.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            return ((DFe_Util_HM.NFeAutorizacao4.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLoteZipAsync(inValue);
        }
    }
}
