//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFe_Util_HM.NFeStatusServico4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", ConfigurationName="NFeStatusServico4.NFeStatusServico4Soap12")]
    public interface NFeStatusServico4Soap12 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeStatusServicoNF não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4/nfeStatusServicoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFResponse nfeStatusServicoNF(DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4/nfeStatusServicoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFResponse> nfeStatusServicoNFAsync(DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeStatusServicoNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeStatusServicoNFRequest() {
        }
        
        public nfeStatusServicoNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeStatusServicoNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeStatusServicoNFResponse() {
        }
        
        public nfeStatusServicoNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeStatusServico4Soap12Channel : DFe_Util_HM.NFeStatusServico4.NFeStatusServico4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeStatusServico4Soap12Client : System.ServiceModel.ClientBase<DFe_Util_HM.NFeStatusServico4.NFeStatusServico4Soap12>, DFe_Util_HM.NFeStatusServico4.NFeStatusServico4Soap12 {
        
        public NFeStatusServico4Soap12Client() {
        }
        
        public NFeStatusServico4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeStatusServico4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeStatusServico4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeStatusServico4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFResponse DFe_Util_HM.NFeStatusServico4.NFeStatusServico4Soap12.nfeStatusServicoNF(DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest request) {
            return base.Channel.nfeStatusServicoNF(request);
        }
        
        public System.Xml.XmlNode nfeStatusServicoNF(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest inValue = new DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFResponse retVal = ((DFe_Util_HM.NFeStatusServico4.NFeStatusServico4Soap12)(this)).nfeStatusServicoNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFResponse> DFe_Util_HM.NFeStatusServico4.NFeStatusServico4Soap12.nfeStatusServicoNFAsync(DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest request) {
            return base.Channel.nfeStatusServicoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFResponse> nfeStatusServicoNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest inValue = new DFe_Util_HM.NFeStatusServico4.nfeStatusServicoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((DFe_Util_HM.NFeStatusServico4.NFeStatusServico4Soap12)(this)).nfeStatusServicoNFAsync(inValue);
        }
    }
}
