//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFe_Util_HM.NFeEventoNacional4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", ConfigurationName="NFeEventoNacional4.NFeRecepcaoEvento4Soap")]
    public interface NFeRecepcaoEvento4Soap {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeRecepcaoEventoNF não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEventoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFResponse nfeRecepcaoEventoNF(DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEventoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFResponse> nfeRecepcaoEventoNFAsync(DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRecepcaoEventoNFRequest() {
        }
        
        public nfeRecepcaoEventoNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeRecepcaoEventoNFResult;
        
        public nfeRecepcaoEventoNFResponse() {
        }
        
        public nfeRecepcaoEventoNFResponse(System.Xml.XmlNode nfeRecepcaoEventoNFResult) {
            this.nfeRecepcaoEventoNFResult = nfeRecepcaoEventoNFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeRecepcaoEvento4SoapChannel : DFe_Util_HM.NFeEventoNacional4.NFeRecepcaoEvento4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeRecepcaoEvento4SoapClient : System.ServiceModel.ClientBase<DFe_Util_HM.NFeEventoNacional4.NFeRecepcaoEvento4Soap>, DFe_Util_HM.NFeEventoNacional4.NFeRecepcaoEvento4Soap {
        
        public NFeRecepcaoEvento4SoapClient() {
        }
        
        public NFeRecepcaoEvento4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeRecepcaoEvento4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRecepcaoEvento4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRecepcaoEvento4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFResponse DFe_Util_HM.NFeEventoNacional4.NFeRecepcaoEvento4Soap.nfeRecepcaoEventoNF(DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest request) {
            return base.Channel.nfeRecepcaoEventoNF(request);
        }
        
        public System.Xml.XmlNode nfeRecepcaoEventoNF(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest inValue = new DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFResponse retVal = ((DFe_Util_HM.NFeEventoNacional4.NFeRecepcaoEvento4Soap)(this)).nfeRecepcaoEventoNF(inValue);
            return retVal.nfeRecepcaoEventoNFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFResponse> DFe_Util_HM.NFeEventoNacional4.NFeRecepcaoEvento4Soap.nfeRecepcaoEventoNFAsync(DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest request) {
            return base.Channel.nfeRecepcaoEventoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFResponse> nfeRecepcaoEventoNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest inValue = new DFe_Util_HM.NFeEventoNacional4.nfeRecepcaoEventoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((DFe_Util_HM.NFeEventoNacional4.NFeRecepcaoEvento4Soap)(this)).nfeRecepcaoEventoNFAsync(inValue);
        }
    }
}
