//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFe_Util_HM.NFeEvento4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", ConfigurationName="NFeEvento4.NFeRecepcaoEvento4Soap12")]
    public interface NFeRecepcaoEvento4Soap12 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeRecepcaoEvento não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoResponse nfeRecepcaoEvento(DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoResponse> nfeRecepcaoEventoAsync(DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRecepcaoEventoRequest() {
        }
        
        public nfeRecepcaoEventoRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeRecepcaoEventoResponse() {
        }
        
        public nfeRecepcaoEventoResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeRecepcaoEvento4Soap12Channel : DFe_Util_HM.NFeEvento4.NFeRecepcaoEvento4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeRecepcaoEvento4Soap12Client : System.ServiceModel.ClientBase<DFe_Util_HM.NFeEvento4.NFeRecepcaoEvento4Soap12>, DFe_Util_HM.NFeEvento4.NFeRecepcaoEvento4Soap12 {
        
        public NFeRecepcaoEvento4Soap12Client() {
        }
        
        public NFeRecepcaoEvento4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeRecepcaoEvento4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRecepcaoEvento4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRecepcaoEvento4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoResponse DFe_Util_HM.NFeEvento4.NFeRecepcaoEvento4Soap12.nfeRecepcaoEvento(DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest request) {
            return base.Channel.nfeRecepcaoEvento(request);
        }
        
        public System.Xml.XmlNode nfeRecepcaoEvento(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest inValue = new DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoResponse retVal = ((DFe_Util_HM.NFeEvento4.NFeRecepcaoEvento4Soap12)(this)).nfeRecepcaoEvento(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoResponse> DFe_Util_HM.NFeEvento4.NFeRecepcaoEvento4Soap12.nfeRecepcaoEventoAsync(DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest request) {
            return base.Channel.nfeRecepcaoEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoResponse> nfeRecepcaoEventoAsync(System.Xml.XmlNode nfeDadosMsg) {
            DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest inValue = new DFe_Util_HM.NFeEvento4.nfeRecepcaoEventoRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((DFe_Util_HM.NFeEvento4.NFeRecepcaoEvento4Soap12)(this)).nfeRecepcaoEventoAsync(inValue);
        }
    }
}
