//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFe_Util_HM.CTeDistribuicao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", ConfigurationName="CTeDistribuicao.CTeDistribuicaoDFeSoap")]
    public interface CTeDistribuicaoDFeSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cteDadosMsg no namespace http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe/cteDistDFeInteresse", ReplyAction="*")]
        DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponse cteDistDFeInteresse(DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe/cteDistDFeInteresse", ReplyAction="*")]
        System.Threading.Tasks.Task<DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponse> cteDistDFeInteresseAsync(DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cteDistDFeInteresseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cteDistDFeInteresse", Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", Order=0)]
        public DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequestBody Body;
        
        public cteDistDFeInteresseRequest() {
        }
        
        public cteDistDFeInteresseRequest(DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe")]
    public partial class cteDistDFeInteresseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement cteDadosMsg;
        
        public cteDistDFeInteresseRequestBody() {
        }
        
        public cteDistDFeInteresseRequestBody(System.Xml.Linq.XElement cteDadosMsg) {
            this.cteDadosMsg = cteDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cteDistDFeInteresseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cteDistDFeInteresseResponse", Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", Order=0)]
        public DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponseBody Body;
        
        public cteDistDFeInteresseResponse() {
        }
        
        public cteDistDFeInteresseResponse(DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe")]
    public partial class cteDistDFeInteresseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement cteDistDFeInteresseResult;
        
        public cteDistDFeInteresseResponseBody() {
        }
        
        public cteDistDFeInteresseResponseBody(System.Xml.Linq.XElement cteDistDFeInteresseResult) {
            this.cteDistDFeInteresseResult = cteDistDFeInteresseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CTeDistribuicaoDFeSoapChannel : DFe_Util_HM.CTeDistribuicao.CTeDistribuicaoDFeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTeDistribuicaoDFeSoapClient : System.ServiceModel.ClientBase<DFe_Util_HM.CTeDistribuicao.CTeDistribuicaoDFeSoap>, DFe_Util_HM.CTeDistribuicao.CTeDistribuicaoDFeSoap {
        
        public CTeDistribuicaoDFeSoapClient() {
        }
        
        public CTeDistribuicaoDFeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTeDistribuicaoDFeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTeDistribuicaoDFeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTeDistribuicaoDFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponse DFe_Util_HM.CTeDistribuicao.CTeDistribuicaoDFeSoap.cteDistDFeInteresse(DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest request) {
            return base.Channel.cteDistDFeInteresse(request);
        }
        
        public System.Xml.Linq.XElement cteDistDFeInteresse(System.Xml.Linq.XElement cteDadosMsg) {
            DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest inValue = new DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest();
            inValue.Body = new DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequestBody();
            inValue.Body.cteDadosMsg = cteDadosMsg;
            DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponse retVal = ((DFe_Util_HM.CTeDistribuicao.CTeDistribuicaoDFeSoap)(this)).cteDistDFeInteresse(inValue);
            return retVal.Body.cteDistDFeInteresseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponse> DFe_Util_HM.CTeDistribuicao.CTeDistribuicaoDFeSoap.cteDistDFeInteresseAsync(DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest request) {
            return base.Channel.cteDistDFeInteresseAsync(request);
        }
        
        public System.Threading.Tasks.Task<DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseResponse> cteDistDFeInteresseAsync(System.Xml.Linq.XElement cteDadosMsg) {
            DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest inValue = new DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequest();
            inValue.Body = new DFe_Util_HM.CTeDistribuicao.cteDistDFeInteresseRequestBody();
            inValue.Body.cteDadosMsg = cteDadosMsg;
            return ((DFe_Util_HM.CTeDistribuicao.CTeDistribuicaoDFeSoap)(this)).cteDistDFeInteresseAsync(inValue);
        }
    }
}
